version: '3'
services:
    connector:
        build: .
        command: flask run
        environment:
            - FLASK_ENV=development
        ports:
            - "5000:5000"
        volumes:
            - ./:/code
        depends_on: 
            - "nectm"
    nectm:
        image: nectm/activatm
        ports:
            - "27979:7979"
            - "27878:7878"
            - "19200:9200"
        volumes: 
            - ./elasticsearch_data:/elasticsearch_data
        
